name: circuitry
version: '0.1.0.0'
category: Graphics
author: Sandy Maguire
maintainer: sandy@sandymaguire.me
license: MIT
dependencies:
- base
- lens
- mtl
- containers
- bytestring
- profunctors
- clash-prelude
- QuickCheck
- generic-lens
- ghc-typelits-natnormalise
- ghc-typelits-knownnat
- ghc-typelits-extra
- cirtography
- text
- aeson
- hspec
- syb
- generic-arbitrary

default-extensions:
  - EmptyCase
  - PostfixOperators
  - TupleSections
  - NamedFieldPuns
  - BangPatterns
  - BinaryLiterals
  - HexFloatLiterals
  - NumericUnderscores
  - GADTSyntax
  - RankNTypes
  - TypeApplications
  - PolyKinds
  - ExistentialQuantification
  - TypeOperators
  - ConstraintKinds
  - ExplicitForAll
  - KindSignatures
  - NamedWildCards
  - ScopedTypeVariables
  - FlexibleContexts
  - FlexibleInstances
  - MultiParamTypeClasses
  - ConstrainedClassMethods
  - InstanceSigs
  - TypeSynonymInstances
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - StandaloneDeriving
  - EmptyDataDeriving
  - DeriveLift
  - GeneralisedNewtypeDeriving
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - NumDecimals
  - ViewPatterns
  - PatternSynonyms
  - TypeFamilies
  - DeriveAnyClass
  - NoStarIsType
  - DataKinds
  - DefaultSignatures
  - TypeApplications
  - LambdaCase
  - OverloadedLabels
  - InstanceSigs
  - RoleAnnotations
  - NoMonomorphismRestriction

ghc-options:
  - -Wall
  - -fplugin GHC.TypeLits.Extra.Solver
  - -fplugin GHC.TypeLits.KnownNat.Solver
  - -fplugin GHC.TypeLits.Normalise


tests:
  test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -flate-specialise
    build-tools:
    - hspec-discover >= 2.0
    dependencies:
    - circuitry

library:
  source-dirs: src
  other-modules: []

