name: circuitry
version: '0.1.0.0'
category: Graphics
author: Sandy Maguire
maintainer: sandy@sandymaguire.me
license: MIT
dependencies:
- base
- diagrams
- diagrams-lib
- diagrams-svg
- diagrams-contrib
- diagrams-core
- lens
- hashable
- mtl
- containers
- transformers
- bytestring
- svg-builder
- string-conv
- base64-bytestring
- catalyst
- lattices
- profunctors
- clash-prelude
- QuickCheck
- checkers
- generic-lens
- ghc-typelits-natnormalise
- ghc-typelits-knownnat
- ghc-typelits-extra
- MemoTrie

default-extensions:
  - EmptyCase
  - PostfixOperators
  - TupleSections
  - NamedFieldPuns
  - BangPatterns
  - BinaryLiterals
  - HexFloatLiterals
  - NumericUnderscores
  - GADTSyntax
  - RankNTypes
  - TypeApplications
  - PolyKinds
  - ExistentialQuantification
  - TypeOperators
  - ConstraintKinds
  - ExplicitForAll
  - KindSignatures
  - NamedWildCards
  - ScopedTypeVariables
  - FlexibleContexts
  - FlexibleInstances
  - MultiParamTypeClasses
  - ConstrainedClassMethods
  - InstanceSigs
  - TypeSynonymInstances
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - StandaloneDeriving
  - EmptyDataDeriving
  - DeriveLift
  - GeneralisedNewtypeDeriving
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - NumDecimals
  - ViewPatterns
  - PatternSynonyms
  - TypeFamilies
  - DeriveAnyClass
  - NoStarIsType
  - DataKinds
  - DefaultSignatures
  - TypeApplications
  - LambdaCase


library:
  source-dirs: src
  other-modules: []
