name: circuitry
version: '0.1.0.0'
category: Graphics
author: Sandy Maguire
maintainer: sandy@sandymaguire.me
license: MIT
dependencies:
- base
- diagrams
- diagrams-lib
- diagrams-svg
- diagrams-contrib
- diagrams-core
- lens
- hashable
- mtl
- containers
- transformers
- bytestring
- svg-builder
- string-conv
- base64-bytestring
- catalyst
- lattices
- profunctors

library:
  source-dirs: src
  other-modules: []
